import { PrivacyVault } from './vault.ts';
import type { RegexExecutor } from './regex-rules.ts';
import { ZeroClaveDetector } from './zeroclave-detector.ts';
import type { TelemetryDetector, TelemetryEvent, TelemetryReporter } from './telemetry.ts';
import type { DetectorMode, PrivacySnapshot, ScanResult, EditableRegexRule, SendPolicy, PrivacyLiveState } from './types.ts';
export declare class SendReviewCancelledError extends Error {
}
export declare class PrivacyController {
    readonly vault: PrivacyVault;
    private readonly executeRegex;
    private readonly zeroclave;
    private readonly telemetryReporter;
    constructor(vault?: PrivacyVault, executeRegex?: RegexExecutor, zeroclave?: ZeroClaveDetector, telemetryReporter?: TelemetryReporter);
    private readonly embedded;
    private readonly storedRules;
    private settingsError;
    private readonly lifetime;
    private readonly inspections;
    private readonly sends;
    private readonly draftDecisions;
    private readonly composerSends;
    private readonly activeSends;
    private preapproved;
    private zeroClaveTest;
    private zeroClaveStateOwner;
    private snapshot;
    private readonly listeners;
    private sendReview;
    readonly getSnapshot: () => PrivacySnapshot;
    readonly subscribe: (listener: () => void) => (() => void);
    initializeTelemetry(): Promise<void>;
    setTelemetryConsent(consent: boolean): void;
    reportTelemetry(event: TelemetryEvent, value?: TelemetryDetector): void;
    private reportScanTelemetry;
    setEnabled(enabled: boolean): void;
    setOpen(open: boolean): void;
    toggleOpen(): void;
    setActiveSession(sessionId: string): void;
    setTab(activeTab: PrivacySnapshot['activeTab']): void;
    setSendPolicy(sendPolicy: SendPolicy): void;
    registerComposerSend(sessionId: string, composer: {
        getText: () => string;
        submit: () => void | Promise<void>;
    }): () => void;
    canRequestComposerSend(sessionId: string): boolean;
    requestComposerSend(sessionId: string): Promise<void>;
    beginSend(sessionId: string): boolean;
    markSending(sessionId: string): void;
    finishSend(sessionId: string, ok: boolean, error?: string): void;
    endSendAttempt(sessionId: string): void;
    setSendReviewFinding(findingId: string, redact: boolean): void;
    setSendReviewReplacement(findingId: string, replacement: string): void;
    addSendReviewFinding(original: string, replacement: string, sourceType: string): boolean;
    addLiveFinding(sessionId: string, original: string, replacement: string, sourceType: string, allOccurrences?: boolean): boolean;
    setReviewPart(index: number): void;
    confirmSendReview(): void;
    cancelSendReview(): void;
    setDetectorMode(detectorMode: DetectorMode): void;
    scan(text: string): ScanResult;
    saveRule(rule: EditableRegexRule): void;
    deleteRule(id: string): void;
    resetRule(id: string): void;
    resetRules(): void;
    testRule(rule: EditableRegexRule, text: string, signal?: AbortSignal): Promise<ScanResult>;
    private commitRules;
    inspect(sessionId: string, text: string, signal?: AbortSignal): Promise<void>;
    loadEmbedded(): Promise<void>;
    testZeroClave(signal?: AbortSignal): Promise<void>;
    prepareSend(sessionId: string, text: string, signal?: AbortSignal): Promise<ScanResult>;
    prepareSendBatch(sessionId: string, texts: readonly string[], signal?: AbortSignal): Promise<ScanResult[]>;
    private requestSendReview;
    private settleSendReview;
    setLiveFindingReplacement(sessionId: string, findingId: string, replacement: string): void;
    setLiveFindingProtection(sessionId: string, findingId: string, protectedValue: boolean, _original?: string): void;
    setLiveFindingsReplacement(sessionId: string, findingIds: readonly string[], replacement: string): void;
    setLiveFindingsProtection(sessionId: string, findingIds: readonly string[], protectedValue: boolean): void;
    private editLiveFindings;
    private editReviewFinding;
    private decisionKey;
    private decisions;
    private bindDrafts;
    private saveDecision;
    private applyDecisions;
    private reviewWithParts;
    private refreshDraft;
    private addFinding;
    dispose(): Promise<void>;
    updateLive(sessionId: string, text: string, result: ScanResult, durationMs?: number, phase?: PrivacyLiveState['phase'], error?: string): void;
    private assertSendCurrent;
    private requireEmbedded;
    private setReviewPhase;
    private makeCustomFinding;
    private beginZeroClaveOperation;
    private finishZeroClaveOperation;
    private releaseZeroClaveOperation;
    private zeroClaveError;
    private setDetectorState;
    private showDetectorDetails;
    private cancelActiveOperations;
    private update;
}
//# sourceMappingURL=controller.d.ts.map